[package]
name = "newsletter"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
name = "newsletter"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
actix-http = "=3.0.0-beta.8"
actix-web = "=4.0.0-beta.8"

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
