[package]
name = "newsletter"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
name = "libnewsletter"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
actix-http = "=3.0.0-beta.8"
actix-web = "=4.0.0-beta.8"
chrono = "0.4.15"
config = "0.11.0"
serde = { version = "1", features = ["derive"] }
uuid = { version = "0.8.1", features = ["v4"] }

[dependencies.sqlx]
version = "0.5.5"
default-features = false
features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"]

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
