[package]
name = "newsletter"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
name = "libnewsletter"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
actix-http = "=3.0.0-beta.8"
actix-web = "=4.0.0-beta.8"
chrono = "0.4.15"
config = "0.11.0"
serde = { version = "1", features = ["derive"] }
uuid = { version = "0.8.1", features = ["v4"] }
tracing = "0.1.19"
tracing-subscriber = { version = "0.2.12", features = ["registry", "env-filter"] }
tracing-futures = "0.2.5"
tracing-bunyan-formatter = "0.2.4"
tracing-log = "0.1.2"
tracing-actix-web = "0.4.0-beta.8"
unicode-segmentation = "1.8.0"

[dependencies.sqlx]
version = "0.5.5"
default-features = false
features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"]

[dev-dependencies]
actix-rt = "2"
claim = "0.5.0"
once_cell = "1.8.0"
reqwest = "0.11"
tokio = "1"
