version: "3.9"

services:
  database:
    image: "${DATABASE_IMAGE}"
    hostname: "${DATABASE_HOSTNAME}"
    ports:
      - "${HOST_DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      db:
        aliases:
          - "{DATABASE_NET_ALIAS}"

  backend:
    image: "${DEV_BACKEND_IMAGE}"
    hostname: "${APP_HOSTNAME}"
    ports:
      - "${HOST_APP_PORT}:${APP_PORT}"
    env_file:
      - ./.env
    volumes:
      - ".:${WORKSPACE}"
    networks:
      db:
        aliases:
          - "${APP_NET_ALIAS}"
    depends_on:
      - database

volumes:
  db:

networks:
  db:
