version: "3.9"

services:
  database:
    image: "${DATABASE_IMAGE}"
    hostname: "${DATABASE_HOSTNAME}"
    ports:
      - "${HOST_DATABASE_PORT}:${DATABASE_PORT}"
    env_file:
      - ./.env.database
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    networks:
      db:

  backend:
    image: "${DEV_BACKEND_IMAGE}"
    hostname: "${COMPOSE_PROJECT_NAME}"
    ports:
      - "${HOST_APP_PORT}:${APP_PORT}"
    env_file:
      - ./.env.database
    volumes:
      - ".:${WORKSPACE}"
    networks:
      - db
    depends_on:
      - database

volumes:
  db:

networks:
  db:
