ARG RUST_BASE_IMAGE=pedromfedricci/dev-rust:1.54.0

FROM ${RUST_BASE_IMAGE}

ARG SQLX_CLI_VERSION=0.5.5

RUN cargo install sqlx-cli \
        --version=${SQLX_CLI_VERSION} \
        --locked \
        --no-default-features \
        --features postgres

ARG POSTGRES_CLIENT_VERSION=11

USER root
RUN apt-get install -y --no-install-recommends \
        postgresql-client-${POSTGRES_CLIENT_VERSION}

USER rustdev
