ARG RUST_BASE_IMAGE=pedromfedricci/dev-rust:1.54.0

FROM ${RUST_BASE_IMAGE}

ARG SQLX_CLI_VERSION=0.5.5

RUN cargo install sqlx-cli \
        --version=${SQLX_CLI_VERSION} \
        --locked \
        --no-default-features \
        --features postgres
