name: Security Audit

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '**/Cargo.toml'
  #     - '**/Cargo.lock'
  # schedule:
  #   - cron: '0 0 * * *'
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run audit check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
