name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish_image:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Get latest version tag
        id: latest_version
        # remove anything leading to 'v' (included)
        run: |
          GIT_TAG=${GITHUB_REF}
          LATEST_VERSION=$(echo $GIT_TAG | sed -r 's/.*v(.*)$/\1/g')
          echo ::set-output name=LATEST_VERSION::${LATEST_VERSION}

      - name: Build and push to Docker Hub
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.latest_version.outputs.LATEST_VERSION }}
          cache-from: type=registry,ref=${{ github.repository }}:latest
          cache-to: type=inline
